name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Check out code
      uses: actions/checkout@v4

    # 2. 安装 Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # 3. 安装依赖
    - name: Install dependencies
      run: npm install
      working-directory: my-vue-app

    # 4. 构建项目
    - name: Build the project
      run: npm run build
      working-directory: my-vue-app

    # 5. 部署到服务器
    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
          cd /wwwroot/my-vue-app
          rm -rf *
          exit
        EOF
        scp -r my-vue-app/dist/* $REMOTE_USER@$REMOTE_HOST:/wwwroot/my-vue-app
